language: php

env:
  - APP_ENV=travis

php:
  - 5.3.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  ## Composer
  - composer self-update
  - composer install --no-interaction

script:
  - phpunit
